name: flutter_tools_task_queue
description: TaskQueue copied from flutter_tools for use in other Dart tools
version: 1.0.0
homepage: https://github.com/IO-Design-Team/flutter_tools_task_queue

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  rexios_lints: ^6.0.1
